from datatemplate import DataTemplate
from default_template import DefaultTemplate
from plot_template import PlotTemplate
from texture_template import TextureTemplate
from sprite_template import SpriteTemplate
from text_template import TextTemplate
from parallelsignals_template import ParallelSignalsTemplate
from rectangles_template import RectanglesTemplate


