from datatemplate import DataTemplate
from default_template import DefaultTemplate
from plot_template import PlotTemplate
from texture_template import TextureTemplate
from sprite_template import SpriteTemplate

